[workspace]
members = [
    "crates/paperdb",
    "crates/paperdb-core",
    "crates/paperdb-inspire-client",
    "crates/paperdb-manifest",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/binado/paperdb"
authors = ["Bernardo Veronese"]

[workspace.dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
clap = { version = "4.5.23", features = ["derive"] }
reqwest = { version = "0.12.9", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tempfile = "3.14.0"
thiserror = "2.0.7"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.19"
toml_edit = { version = "0.22.22", features = ["serde"] }
unicode-normalization = "0.1.24"
url = "2.5.4"
