[workspace]
members = [
    "crates/bibi",
    "crates/bibi-core",
    "crates/bibi-documents",
    "crates/bibi-inspire-client",
    "crates/bibi-bibliography",
    "crates/bibi-bibfile",
    "crates/bibi-manifest",
]
resolver = "2"

[workspace.package]
version = "0.4.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/binado/bibi"
authors = ["Bernardo Veronese"]

[workspace.dependencies]
anstyle = "1"
anyhow = "1.0.94"
biblatex = "0.12"
clap = { version = "4.5.23", features = ["derive", "env"] }
clap_complete = "4"
bibi-bibfile = { path = "crates/bibi-bibfile", version = "0.4.0" }
bibi-bibliography = { path = "crates/bibi-bibliography", version = "0.4.0" }
bibi-core = { path = "crates/bibi-core", version = "0.4.0" }
bibi-documents = { path = "crates/bibi-documents", version = "0.4.0" }
bibi-inspire-client = { path = "crates/bibi-inspire-client", version = "0.4.0" }
bibi-manifest = { path = "crates/bibi-manifest", version = "0.4.0" }
flate2 = "1"
httpdate = "1"
opener = "0.8.5"
percent-encoding = "2.3.2"
reqwest = { version = "0.12.9", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tar = "0.4"
tempfile = "3.14.0"
terminal_size = "0.4"
thiserror = "2.0.7"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "time"] }
toml = "0.8.19"
url = "2.5.4"
