[workspace]
members = [
    "crates/bibi",
    "crates/bibi-application",
    "crates/bibi-bibtex",
    "crates/bibi-core",
    "crates/bibi-documents",
    "crates/bibi-inspire",
    "crates/bibi-manifest",
    "crates/bibi-provider",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/binado/bibi"
authors = ["Bernardo Veronese"]

[workspace.dependencies]
anstyle = "1"
anyhow = "1.0.94"
biblatex = "0.12"
bibi-application = { path = "crates/bibi-application", version = "0.1.0" }
bibi-bibtex = { path = "crates/bibi-bibtex", version = "0.1.0" }
bibi-core = { path = "crates/bibi-core", version = "0.1.0" }
bibi-documents = { path = "crates/bibi-documents", version = "0.1.0" }
bibi-inspire = { path = "crates/bibi-inspire", version = "0.1.0" }
bibi-manifest = { path = "crates/bibi-manifest", version = "0.1.0" }
bibi-provider = { path = "crates/bibi-provider", version = "0.1.0" }
clap = { version = "4.5.23", features = ["derive"] }
clap_complete = "4"
httpdate = "1"
indicatif = { version = "0.17", default-features = false, features = ["unicode-width"] }
opener = "0.8.5"
percent-encoding = "2.3.2"
reqwest = { version = "0.12.9", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tempfile = "3.14.0"
terminal_size = "0.4"
thiserror = "2.0.7"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "time"] }
toml = "0.8.19"
unicode-width = "0.2"
url = "2.5.4"
uuid = { version = "1", features = ["v4"] }
