[package]
name = "cita"
description = "A Git-friendly bibliography database"
readme = "../../README.md"
keywords = ["bibliography", "bibtex", "citations", "inspirehep"]
categories = ["command-line-utilities", "science"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "cita"
path = "src/main.rs"

[dependencies]
anstyle.workspace = true
anyhow.workspace = true
clap.workspace = true
cita-core = { path = "../cita-core" }
cita-documents = { path = "../cita-documents" }
cita-inspire-client = { path = "../cita-inspire-client" }
cita-manifest = { path = "../cita-manifest" }
opener.workspace = true
tempfile.workspace = true
terminal_size.workspace = true
tokio.workspace = true

[dev-dependencies]
toml.workspace = true
