[package]
name = "cita"
description = "A Git-friendly bibliography database"
readme = "../../README.md"
keywords = ["bibliography", "bibtex", "citations", "inspirehep"]
categories = ["command-line-utilities", "science"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = ["crates-io"]

[[bin]]
name = "cita"
path = "src/main.rs"

[dependencies]
anstyle.workspace = true
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
cita-core.workspace = true
cita-documents.workspace = true
cita-inspire-client.workspace = true
cita-bibliography.workspace = true
cita-manifest.workspace = true
opener.workspace = true
tempfile.workspace = true
terminal_size.workspace = true
tokio.workspace = true
