[package]
name = "cita-inspire-client"
description = "Direct BibTeX client for INSPIRE literature"
readme = "README.md"
keywords = ["inspirehep", "literature", "physics", "api"]
categories = ["api-bindings", "science"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = ["crates-io"]

[dependencies]
cita-bibliography.workspace = true
cita-core.workspace = true
httpdate.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
